#!/usr/bin/env bash
#SBATCH --nodes=2
#SBATCH --ntasks=160
#SBATCH --job-name=QE_n200_3k_2nod
#SBATCH --mail-type=begin        # send email when job begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=georgiy.marchiy@mail.ioffe.ru
module purge
module load intel libraries/mkl intel-mpich/scalapack intel/mpich

mpirun --bind-to core -np 160 pw.x -inp pwscf_200_3k.in > pwscf_200_3k_2nodes.out
