#!/usr/bin/env bash
#SBATCH --nodes=2
#SBATCH --ntasks=180
#SBATCH --job-name=QE_n161_3k_2nod
#SBATCH --mail-type=begin        # send email when job begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=georgiy.marchiy@mail.ioffe.ru
module purge
module load intel libraries/mkl intel-mpich/scalapack intel/mpich

mpirun --bind-to core -np 180 pw.x -inp pwscf_161_2d_3k.in > pwscf_161_2d_3k_2nodes.out
