#!/usr/bin/env bash
#SBATCH --nodes=1
#SBATCH --ntasks=90
#SBATCH --job-name=QE_n161_3k_upd
#SBATCH --mail-type=begin        # send email when job begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=georgiy.marchiy@mail.ioffe.ru
module purge
module load intel libraries/mkl intel-mpich/scalapack intel/mpich

mpirun --bind-to core -np 90 pw.x -inp pwscf_161_3k_upd.in > pwscf_161_3k_upd.out
